jQuery.extend(jQuery.validator.messages, {
        required: "请输入信息",
		remote: "已存在",
		email: "请输入正确格式的电子邮件",
		url: "请输入合法的网址",
		date: "请输入合法的日期",
		dateISO: "请输入合法的日期 (ISO).",
		number: "请输入合法的数字",
		digits: "请输入有效数字",
		digitss: "请输入整数",
		digitsCustom: "请输入整数",
		creditcard: "请输入合法的信用卡号",
		equalTo: "请再次输入相同的值",
		equalToLimit: "请满足以下条件：峰值带宽 >= 保证带宽 + 固定带宽",
		accept: "请输入拥有合法后缀名的字符串",
		maxlength: jQuery.validator.format("请输入一个长度最多是 {0}的字符串"),
		minlength: jQuery.validator.format("请输入一个长度最少是 {0}的字符串"),
		len: jQuery.validator.format("请输入一个长度是{0}的字符串"),
		rangelength: jQuery.validator.format("请输入一个长度介于{0}和{1}之间的字符串"),
		range: jQuery.validator.format("请输入一个介于{0}和{1}之间的值"),
		rangeLimit: jQuery.validator.format("请输入一个小于{1}的{2}的正整数倍的值"),
		evenRange: jQuery.validator.format("请输入一个介于{0}和{1}之间的偶数"),
		max: jQuery.validator.format("请输入一个最大为{0}的值"),
		min: jQuery.validator.format("请输入一个最小为{0}的值"),
		mac: "请输入合法的mac地址,mac格式为00-24-21-19-bD-E4",
		macAddr:"支持MAC地址模糊查询，MAC地址格式为：“00-1A-16-”",
		ip: "请输入合法的IP地址,ip格式为192.168.22.254",
		ipv4orv6: "请输入合法的IP地址,ipv4格式为192.168.22.254,ipv6格式为2000::1:2345:6789:abcd",
		subnetworkMask:"请输入合法的子网掩码,子网掩码格式为255.255.255.0",
		subnetworkMaskRange:"掩码的范围必须大于起始ip和结束ip地址的范围",
		sameNetworkSegment:"{2}和{3}必须在同一网段",
		unicastAddress:"请输入单播IP地址",
		ipSearch:"支持IP地址模糊查询，IP地址格式为：“192.168.0.1”",
		anyString:"请输入任意字符串",
		moreThan:"结束VLAN必须大于起始VLAN",
		moreThanTerminalCode:"结束编号必须大于起始编号",
		moreThanTime:"结束时间必须晚于起始时间",
		moreThanIp:"结束IP必须大于起始IP",
		moreThanIpRange:"结束IP必须大于起始IP。IP范围不能超过1024。",
		notMoreThan200:"结束VLAN和起始VLAN的间隔不得超过200",
		lessThan:"起始VLAN必须小于结束VLAN",
		filtSpecialChar:"不能输入特殊字符，包括~ ` ! @ # $ % ^ & * ( ) + = { } [ ] \" \' \< \> ? | \\",
		space:"不能输入特殊字符，包括~ ` ! @ # $ % ^ & * ( ) + = { } [ ] \" \' \< \> ? | \\ 及空格",
		legalChar:"请输入一个仅包含数字、字母或中文的字符串",
		phone:"请正确填写电话,只能输入数字和-",
		mobile:"请正确填写手机号码",
		tel:"请正确填写电话号码",
		userName:"名称只能是字符、数字、下划线（_）或汉字。",
		vlanInputRule:"请输入合法值。如：3,6,7",
		vlanInputOtherRule:"vlan取值为1-4094，不能有重复值，且最多{0}个！",
		eqlToDefaultVlanRule:"trunkVlan和PVID的值不能重复！",
		fastLeaveAbility:"4位数字,1表支持，0不支持。对应可控组播方式下fast- leave、non-fast- leave，IGMP Snooping组播方式下fast- leave、non-fast-leave功能是否支持。",
	    vlanTransInput:"请输入合法值。如：3-4,6-5。vlan取值为1-4094，原始vlan不能重复，不能首尾相接，且最多8个！",
	    ipRange:"请输入合法的IP地址，范围为224.0.1.0～238.255.255.255",
	    isMiddle:"ip必须位于起始ip和结束ip之间",
	    valueRange:"请输入范围值,如：3-4。取值范围{0}-{1}。",
	    vlanRange:"取值范围{0}-{1}。可以为一个确定值，可以是一个是范围如“起始值-结束值”，结束值需大于起始值。",
	    vlanAssociateRule:"VLAN匹配范围只能使用一次，如果已经使用过请输入确定值",
	    mixModeMacLoid:"MAC地址和LOID必须且只能填写一项",
	    leastMacOrLoid:"MAC地址和LOID两项中至少填写一项",
	    mixModePwd:"填写MAC地址之后，不能再填密码",
	    noRepeatMac:"MAC地址不能重复",
	    noRepeatLoid:"LOID不能重复",
	    noRepeatLoidAndPassword:"LOID+PASSWORD组合不能重复",
	    noRepeat:"不能重复",
	    customTypes:"请输入2字节十六进制字符",
	    vlanRule:"请输入{0}-{1}的值，如3,6,7，不能有重复值，且最多{2}个",
	    lessEqualPledgeBandwidth:"固定带宽需小于等于保证带宽",
	    notIgmpIp:"请输入非组播IP",
	    noRequiredPmParam:"在此条件下无采集参数，请重新选择！",
	    noLessThanGeneral:"最大值必须大于等于最小值",
	    macCharValidate:"只能输入0-9a-fA-F和-",
	    ipCharValidate:"只能输入0-9和.",
	    zyCode:"设备编号为12位16进制字符",
	    notEqual:"{1}和{2}的值不能相同！"
});